In [1]:
import pandas as pd  
import numpy as np

In [7]:
file1 = pd.read_excel('marketing_customer_analysis.xlsx')
display(file1)
column_names = file1.columns
column_names

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0.0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,0.0,9.0,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1.0,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,0.0,1.0,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2.0,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,0.0,2.0,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3.0,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,0.0,2.0,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4.0,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,NaN,7.0,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905.0,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,NaN,7.0,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A
10906,10906.0,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,0.0,6.0,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A
10907,10907.0,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,0.0,2.0,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,NaN
10908,10908.0,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,4.0,6.0,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A
10909,10909.0,IV32877,NaN,6857.519928,NaN,Basic,Bachelor,2011-01-08,Unemployed,M,...,0.0,3.0,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,NaN

Index(['Unnamed: 0', 'Customer', 'State', 'Customer Lifetime Value',
       'Response', 'Coverage', 'Education', 'Effective To Date',
       'EmploymentStatus', 'Gender', 'Income', 'Location Code',
       'Marital Status', 'Monthly Premium Auto', 'Months Since Last Claim',
       'Months Since Policy Inception', 'Number of Open Complaints',
       'Number of Policies', 'Policy Type', 'Policy', 'Renew Offer Type',
       'Sales Channel', 'Total Claim Amount', 'Vehicle Class', 'Vehicle Size',
       'Vehicle Type'],
      dtype='object')

In [12]:
column_names = file1.columns
data_coloumn = pd.DataFrame(columns=column_names)
data_coloumn

Empty DataFrame
Columns: [Unnamed: 0, Customer, State, Customer Lifetime Value, Response, Coverage, Education, Effective To Date, EmploymentStatus, Gender, Income, Location Code, Marital Status, Monthly Premium Auto, Months Since Last Claim, Months Since Policy Inception, Number of Open Complaints, Number of Policies, Policy Type, Policy, Renew Offer Type, Sales Channel, Total Claim Amount, Vehicle Class, Vehicle Size, Vehicle Type]
Index: []

[0 rows x 26 columns]

In [10]:
data = pd.DataFrame(file1)
display(data)
data.shape

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0.0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,0.0,9.0,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1.0,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,0.0,1.0,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2.0,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,0.0,2.0,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3.0,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,0.0,2.0,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4.0,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,NaN,7.0,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905.0,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,NaN,7.0,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A
10906,10906.0,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,0.0,6.0,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A
10907,10907.0,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,0.0,2.0,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,NaN
10908,10908.0,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,4.0,6.0,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A
10909,10909.0,IV32877,NaN,6857.519928,NaN,Basic,Bachelor,2011-01-08,Unemployed,M,...,0.0,3.0,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,NaN

(10910, 26)

In [33]:
#before cleaing lets quickly analyse the spaces before we standardise anything
display(data.head(20))
display(data.tail(20))

,Serial Number,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,0.0,9.0,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,0.0,1.0,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,0.0,2.0,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,0.0,2.0,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,NaN,7.0,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN
5,5,HO81102,NaN,4745.181764,NaN,Basic,High School or Below,2011-02-14,Employed,M,...,0.0,7.0,Personal Auto,Personal L3,Offer1,Agent,292.800000,Four-Door Car,Medsize,A
6,6,IW72280,California,5035.035257,No,Basic,Doctor,2011-02-14,Employed,F,...,3.0,4.0,Corporate Auto,Corporate L2,Offer2,Branch,287.556107,Four-Door Car,Medsize,NaN
7,7,IH64929,California,4956.247235,No,Basic,High School or Below,2011-02-24,Employed,M,...,0.0,3.0,Personal Auto,Personal L2,Offer2,Branch,247.402353,Two-Door Car,Medsize,NaN
8,8,FM55990,California,5989.773931,Yes,Premium,College,2011-01-19,Employed,M,...,0.0,1.0,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
9,9,QX31376,Oregon,17114.328150,No,Extended,Master,2011-01-04,Employed,F,...,0.0,2.0,Corporate Auto,Corporate L3,Offer2,Agent,408.000000,Four-Door Car,Small,NaN
10,10,HG93801,Arizona,5154.764074,No,Extended,High School or Below,2011-01-02,Employed,M,...,0.0,1.0,Corporate Auto,Corporate L3,Offer2,Branch,442.521087,SUV,Large,A
11,11,GE63585,NaN,2420.711888,NaN,Basic,Bachelor,2011-02-07,Employed,M,...,0.0,1.0,Corporate Auto,Corporate L3,Offer1,Call Center,199.551735,Two-Door Car,Medsize,NaN
12,12,EO51920,Oregon,19955.257130,No,Extended,High School or Below,2011-01-31,Employed,F,...,0.0,2.0,Corporate Auto,Corporate L3,Offer1,Agent,64.669515,Four-Door Car,Medsize,NaN
13,13,KR82385,California,5454.587929,No,Basic,Master,2011-01-26,Employed,M,...,0.0,4.0,Personal Auto,Personal L3,Offer4,Call Center,331.200000,Two-Door Car,Medsize,A
14,14,TL59568,Arizona,12836.009510,No,Premium,High School or Below,2011-02-28,Unemployed,M,...,0.0,2.0,Personal Auto,Personal L2,Offer3,Agent,835.200000,Two-Door Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,2011-01-16,Employed,F,...,0.0,1.0,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
16,16,FH51383,California,5326.677654,No,Basic,High School or Below,2011-02-07,Employed,F,...,0.0,6.0,Personal Auto,Personal L3,Offer4,Call Center,300.528579,Two-Door Car,Large,A
17,17,TR26615,Oregon,2497.531509,No,Basic,High School or Below,2011-01-17,Unemployed,M,...,0.0,1.0,Corporate Auto,Corporate L2,Offer2,Branch,272.381465,Two-Door Car,Medsize,A
18,18,ZC97968,California,2736.352663,No,Basic,College,2011-02-14,Disabled,M,...,0.0,1.0,Personal Auto,Personal L3,Offer1,Agent,350.400000,Two-Door Car,Medsize,A
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2011-02-26,Employed,F,...,1.0,1.0,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A

,Serial Number,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
10890,10890,VQ78876,Oregon,4660.399573,No,Basic,Bachelor,2011-02-03,Employed,F,...,0.0,1.0,Corporate Auto,Corporate L3,Offer1,Branch,43.155950,NaN,NaN,NaN
10891,10891,UV43859,Oregon,8840.193762,No,Basic,High School or Below,2011-01-22,Employed,F,...,4.0,4.0,Personal Auto,Personal L3,Offer2,Web,796.130111,SUV,Medsize,NaN
10892,10892,BC87551,California,32306.285870,No,Basic,High School or Below,2011-01-28,Employed,F,...,0.0,2.0,Corporate Auto,Corporate L3,Offer1,Branch,647.954067,SUV,Medsize,A
10893,10893,CG69038,Washington,4817.992644,No,Basic,College,2011-02-26,Employed,M,...,0.0,4.0,Personal Auto,Personal L3,Offer3,Branch,81.532330,Two-Door Car,Medsize,NaN
10894,10894,EX63393,NaN,6314.492009,NaN,Extended,Master,2011-02-27,Employed,F,...,0.0,6.0,Personal Auto,Personal L1,Offer3,Agent,374.400000,Four-Door Car,Small,NaN
10895,10895,EG40670,California,6232.687923,No,Extended,Bachelor,2011-01-08,Disabled,F,...,0.0,7.0,Special Auto,Special L3,Offer1,Agent,537.765151,Four-Door Car,Medsize,A
10896,10896,HT87217,Oregon,19776.566540,No,Extended,High School or Below,2011-01-16,Employed,F,...,0.0,2.0,Personal Auto,Personal L2,Offer3,Agent,256.813837,Four-Door Car,Medsize,A
10897,10897,MM70762,Arizona,9075.768214,Yes,Basic,Master,2011-01-26,Employed,M,...,0.0,8.0,Personal Auto,Personal L1,Offer1,Agent,158.077504,Sports Car,Medsize,A
10898,10898,SO95845,California,5807.659307,No,Basic,College,2011-01-07,Employed,F,...,0.0,7.0,Personal Auto,Personal L3,Offer4,Call Center,133.977857,Two-Door Car,Medsize,NaN
10899,10899,WU60905,California,8610.667489,No,Basic,High School or Below,2011-02-06,Unemployed,F,...,0.0,9.0,Corporate Auto,Corporate L1,Offer3,Web,532.800000,SUV,Medsize,A
10900,10900,VN73653,Oregon,6423.739052,No,Basic,College,2011-02-13,Unemployed,M,...,0.0,1.0,Corporate Auto,Corporate L2,Offer3,Agent,1621.560425,Luxury SUV,Medsize,NaN
10901,10901,RY92254,Washington,4547.892543,No,Premium,Bachelor,2011-01-13,Employed,M,...,0.0,1.0,Personal Auto,Personal L3,Offer4,Agent,801.577478,Two-Door Car,Medsize,NaN
10902,10902,PP30874,California,3579.023825,No,Extended,High School or Below,2011-01-24,Employed,F,...,2.0,1.0,Personal Auto,Personal L2,Offer2,Agent,655.200000,Four-Door Car,Medsize,A
10903,10903,SU71163,Arizona,2771.663013,No,Basic,College,2011-01-07,Employed,M,...,4.0,1.0,Personal Auto,Personal L2,Offer2,Branch,355.200000,Two-Door Car,Medsize,A
10904,10904,QI63521,Nevada,19228.463620,No,Basic,High School or Below,2011-02-24,Unemployed,M,...,0.0,2.0,Personal Auto,Personal L2,Offer1,Branch,897.600000,Luxury SUV,Medsize,A
10905,10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,NaN,7.0,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A
10906,10906,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,0.0,6.0,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A
10907,10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,0.0,2.0,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,NaN
10908,10908,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,4.0,6.0,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A
10909,10909,IV32877,NaN,6857.519928,NaN,Basic,Bachelor,2011-01-08,Unemployed,M,...,0.0,3.0,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,NaN

In [16]:
# rename the unnamed coloumn to serial 
data.rename( columns={'Unnamed: 0':'Serial Number'}, inplace=True )
data

,Serial Number,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0.0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,0.0,9.0,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1.0,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,0.0,1.0,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2.0,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,0.0,2.0,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3.0,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,0.0,2.0,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4.0,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,NaN,7.0,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905.0,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,NaN,7.0,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A
10906,10906.0,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,0.0,6.0,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A
10907,10907.0,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,0.0,2.0,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,NaN
10908,10908.0,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,4.0,6.0,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A
10909,10909.0,IV32877,NaN,6857.519928,NaN,Basic,Bachelor,2011-01-08,Unemployed,M,...,0.0,3.0,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,NaN

In [20]:
# convert the tables to proper numeric values
# convert column "serial number" of DataFrame to numeric
data["Serial Number"] = pd.to_numeric(data["Serial Number"])
data['Serial Number'] = data['Serial Number'].astype('int')
data

,Serial Number,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,0.0,9.0,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,0.0,1.0,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,0.0,2.0,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,0.0,2.0,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,NaN,7.0,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,NaN,7.0,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A
10906,10906,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,0.0,6.0,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A
10907,10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,0.0,2.0,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,NaN
10908,10908,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,4.0,6.0,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A
10909,10909,IV32877,NaN,6857.519928,NaN,Basic,Bachelor,2011-01-08,Unemployed,M,...,0.0,3.0,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,NaN

In [32]:
#to find catgorical and numeric data
#df.select_dtypes(include=['category','int','float']).dtypes

print('original data and its length are as folows:')
cols = data.columns
cols
display(cols)
display(len(cols))

print('numeric data and its length are as folows:')
num_cols = data._get_numeric_data().columns
display(num_cols)
display(len(num_cols))


catergorical_data = list(set(cols) - set(num_cols))
catergorical_data

original data and its length are as folows:

Index(['Serial Number', 'Customer', 'State', 'Customer Lifetime Value',
       'Response', 'Coverage', 'Education', 'Effective To Date',
       'EmploymentStatus', 'Gender', 'Income', 'Location Code',
       'Marital Status', 'Monthly Premium Auto', 'Months Since Last Claim',
       'Months Since Policy Inception', 'Number of Open Complaints',
       'Number of Policies', 'Policy Type', 'Policy', 'Renew Offer Type',
       'Sales Channel', 'Total Claim Amount', 'Vehicle Class', 'Vehicle Size',
       'Vehicle Type'],
      dtype='object')

26

numeric data and its length are as folows:

Index(['Serial Number', 'Customer Lifetime Value', 'Income',
       'Monthly Premium Auto', 'Months Since Last Claim',
       'Months Since Policy Inception', 'Number of Open Complaints',
       'Number of Policies', 'Total Claim Amount'],
      dtype='object')

9

['Renew Offer Type',
 'Customer',
 'Response',
 'Policy Type',
 'Marital Status',
 'EmploymentStatus',
 'Education',
 'Location Code',
 'Gender',
 'Sales Channel',
 'Policy',
 'Vehicle Type',
 'State',
 'Coverage',
 'Effective To Date',
 'Vehicle Class',
 'Vehicle Size']

In [42]:
# dealing with NaN
# first I will findout the number of missing values in the categorical data
#the response couloumn has values Nan, Yes or no


display(data['Response'].unique())
display(data['Response'].value_counts())

data['Response'].value_counts(dropna=False) # Use dropna=False to also display the amount of NA's

# I will replace the NaN value with that of has highest number of frequency value
data['Response'] = data['Response'].fillna('No')
print('after replacing')
display(data['Response'].unique())
display(data['Response'].value_counts())
#bool_series = pd.isnull(data["Response"])

# filtering data
# displaying data only with response = NaN
#print('displaying data only with response = NaN')
##display(data[bool_series])

array(['No', 'Yes'], dtype=object)

No     9444
Yes    1466
Name: Response, dtype: int64

after replacing

array(['No', 'Yes'], dtype=object)

No     9444
Yes    1466
Name: Response, dtype: int64

In [46]:
# i scout for some more of redundant values in categorical sets
data.head(30)
data.tail(30)

#From visual inspection i see NaN in Vehicle type coloumn
#so I clean some more

display(data['Vehicle Type'].unique())
display(data['Vehicle Type'].value_counts())
len(data[data['Vehicle Type'].isna()==True])  # number of missing values
data['Vehicle Type'].value_counts(dropna=False) # Use dropna=False to also display the amount of NA's

#output
#NaN    5482
#A      5428
# so we put everything as an 'A' value

data['Vehicle Type'] = data['Vehicle Type'].fillna('No')

array([nan, 'A'], dtype=object)

A    5428
Name: Vehicle Type, dtype: int64

In [56]:
# lets remove some whitespaces in the dataframe on all the categorical coloumns
#str. strip()


for coloumns in range (len(catergorical_data)):
    input_col = catergorical_data[coloumns]
    data['input_col'].str.strip()

KeyError: 'input_col'